# -*- coding: utf-8 -*-
"""Atividade do dia 08/05/2024 coding

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UzPHuRsKYQu2ozwYPehhMX3N_Uetx1BL
"""

for produto in range (0, 4):
  p = str(input("Digite o nome do produto: "))
  v = float(input("Digite o valor do produto: "))

for elemento in "STRING":
 print("Estamos no elemento" , elemento )

for elemento in range(len("STRING")):
  print("estamos no elemento" , elemento)

produto = 0
while produto < 4:
  p = str(input("Digite o nome do produto: "))
  v = float(input("Digite o valor do produto: "))
  produto += 1

elemento = 0
while elemento <= len((1, 2, 3, 4, 5, 6)):
  print("Estamos no elemento" , elemento)
  elemento += 1

s = "STRING"
indice = 0
while indice in range (len(s)):
 print("Estamos no elemento" , s(indice))
 indice +=1

palavra = "tranquilo"
for indice, letra in enumerate(palavra):
  print(indice, letra)

lista = ("eat", "sleep", "repeat" )
objeto1= enumerate (lista)
objeto2= enumerate (palavra)
print("Tipo: ", type(objeto1))
print(list(enumerate(palavra, 2)))

s = "viva o python"
for ch in s[3:8]:
  print("Oi")

s = "viva o python"
for ch in s:
  print("Oi")

"""**Desafio**"""

num_pares = 0
num_impares = 0
for numeros in range (0, 10):
 numeros = int(input("Digite um número inteiro: "))
 if numeros % 2 == 0:
  num_pares += 1
 if numeros % 2 >= 1:
    num_impares += 1

print("A quantidade de números pares é " , num_pares)
print("A quantidade de números impares é " , num_impares)