# -*- coding: utf-8 -*-
"""Olá, este é o Colaboratory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

Listas python. Inicia no zero, ":" até, intervalo fechado, vai até um determinado item e para antes.
"""

a = [81,82,83]
b = a[:]
print(a == b)
print(a is b)
b[0] = 5
print(a)
print(b)

uma_lista = ['a', 'b', 'c', 'd', 'e', 'f' ]
print(uma_lista[1:3])
print(uma_lista[:4])
print(uma_lista[3:])
print(uma_lista [:])

"""Tem 3 elementos, mas a contagem inicia do 0. Tendo apenas até o índice 2."""

a = [1,2,3]
b = a[:]
b[0] = 5
print(a[3])

Crie um lista chamada minhaLista com os seguintes itens: 76, 92.3, "oi", True, 4, 76. Depois execute os seguintes comandos:
a) Inserir "pitomba" e 76 no final da lista.
b) Inserir o valor "Cibele" na posição do índice 3.
c) Inserir o valor 99 no início da Lista.
d) Encontrar o índice de oi
d)Remover o True da lista.

"""Letra a"""

minhaLista = [76, 92.3, "oi", True, 4, 76]
minhaLista[5] = "pitomba"
lista2 = ["pitomba", 76]
minhaLista = [76, 92.3, "oi", True, 4, 76] + lista2
print(minhaLista)

"""Letra b"""

minhaLista = [76, 92.3, 'oi', True, 4, 76, 'pitomba', 76]
nome = ["Cibele"]
minhaLista = [76, 92.3, 'oi'] + nome + [True, 4, 76, 'pitomba', 76]
print(minhaLista)

"""Letra c"""

minhaLista = [76, 92.3, 'oi', 'Cibele', True, 4, 76, 'pitomba', 76]
valor = [99]
minhaLista = valor + [76, 92.3, 'oi', 'Cibele', True, 4, 76, 'pitomba', 76]
print(minhaLista)

"""Letra d"""

minhaLista = [99, 76, 92.3, 'oi', 'Cibele', True, 4, 76, 'pitomba', 76]

if (minhaLista[0] == 'oi'):
 print("A posição do item é a 1")
elif (minhaLista[1] == 'oi'):
  print("A posição do item é a 1")
elif (minhaLista[2] == 'oi'):
  print("A posição do item é a 3")
elif (minhaLista[3] == 'oi'):
  print("A posição do item é a 4")
elif (minhaLista[4] == 'oi'):
  print("A posição do item é a 5")
elif (minhaLista[5] == 'oi'):
  print("A posição do item é a 6")
elif (minhaLista[6] == 'oi'):
  print("A posição do item é a 7")
elif (minhaLista[7] == 'oi'):
  print("A posição do item é a 8")
elif (minhaLista[8] == 'oi'):
  print("A posição do item é a 9")
elif (minhaLista[9] == 'oi'):
  print("A posição do item é a 10")
else:
    print("O item não foi encontrado")

"""Letra e"""

minhaLista = [99, 76, 92.3, 'oi', 'Cibele', True, 4, 76, 'pitomba', 76]
minhaLista = minhaLista[:5] + minhaLista[6:]
print(minhaLista)

uma_lista = [4,2,8,6,5]
uma_lista = uma_lista + ["Cibele"]
print(uma_lista)

"""Tupla

Métodos
"""

tupla_nomes = ("Marlene", "Zezinho", "Marlene", "Cibele", "Zuely")
tupla_nomes.count("Marlene")
print(tupla_nomes.count("Marlene"))
print(tupla_nomes.count("Suely"))
print(tupla_nomes.count("Zezinho"))

"""Crie uma tupla com os seguintes elementos : e depous use a função count do objeto tupla para verificar quantas vezes o número 4 aparece na tupla."""

tupla_num = (1,2,2,3,4,4,4,5)
print(tupla_num.count(4))